### ISSUE TITLE
Frontend not working correctly through primary URL

### ISSUE THREAD

**Issue by AndrewMatison** [AusDTO/dto-digitalmarketplace-buyer-frontend#16]
Styling is not loading when accessing the development version through https://gov.au/marketplace.

**Comment by sarneaud** [comment]
Because it was the original plan, we're serving everything (including static content) from / in the app, but the new proxy serves the site from /marketplace

The HTML generation doesn't care, but it has to include links to static content.  If the links include /marketplace, they break for non-proxied requests the devs use.  If they don't, they break for proxied requests.

The sanest thing to do is just serve everything from /marketplace

**Comment by sarneaud** [comment]
This fix has been pushed to the live version now.
